package com.sonumax2.javabot.domain.session;

public enum UserState {
    IDLE,
    FLOW_WAIT_INPUT,

    // Advance
    ADVANCE_WAIT_DATE,
    ADVANCE_WAIT_DATE_TEXT,
    ADVANCE_WAIT_AMOUNT,
    ADVANCE_WAIT_NOTE,
    ADVANCE_CONFIRM,

    // EXPENSE
    EXPENSE_WAIT_OBJECT,
    EXPENSE_WAIT_OBJECT_TEXT,

    EXPENSE_WAIT_NOMENCLATURE_PICK,
    EXPENSE_WAIT_NEW_NOMENCLATURE_TEXT,
    EXPENSE_WAIT_NOMENCLATURE_SUGGEST,

    EXPENSE_WAIT_CP_PICK,
    EXPENSE_WAIT_CP_TEXT,
    EXPENSE_WAIT_CP_SUGGEST,
    EXPENSE_WAIT_CP_KIND,

    EXPENSE_WAIT_DOC_TYPE,
    EXPENSE_WAIT_DOC_FILE,

    EXPENSE_WAIT_AMOUNT,
    EXPENSE_WAIT_DATE,
    EXPENSE_WAIT_DATE_TEXT,
    EXPENSE_WAIT_NOTE,
    EXPENSE_CONFIRM,
}
